export const ADMIN_ROUTE = '/admin'
export const ABOUT_ROUTE = '/about'
export const CATALOG_ROUTE = '/catalog'
export const CONTACT_ROUTE = '/contact-me'
export const SIGNUP_ROUTE = '/sign-up'
export const SIGNIN_ROUTE = '/sign-in'
export const MAIN_ROUTE = '/'